apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/part-of: bookplus
spec:
  selector:
    app.kubernetes.io/name: mailhog
  ports:
  - port: 1025
    targetPort: 1025
    name: smtp
  - port: 8025
    targetPort: 8025
    name: ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/part-of: bookplus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mailhog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailhog
        app.kubernetes.io/part-of: bookplus
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest
        ports:
        - containerPort: 1025
          name: smtp
        - containerPort: 8025
          name: ui
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
