apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Produccion: incluye el autoescalado (HPA) y sube las replicas base a 2.
namespace: bookplus
resources:
  - ../../base
  - ../../base/hpa
labels:
  - includeSelectors: false
    pairs:
      environment: prod
images:
  - name: ghcr.io/bookplus-org/auth-service
    newTag: "1.0.0"
replicas:
  - { name: api-gateway,          count: 2 }
  - { name: auth-service,         count: 2 }
  - { name: catalog-service,      count: 2 }
  - { name: inventory-service,    count: 2 }
  - { name: cart-service,         count: 2 }
  - { name: order-service,        count: 2 }
  - { name: payment-service,      count: 2 }
  - { name: notification-service, count: 2 }
  - { name: report-service,       count: 2 }
  - { name: admin-bff,            count: 2 }
patches:
  - target: { kind: ConfigMap, name: api-gateway-config }
    patch: |
      - op: replace
        path: /data/CORS_ALLOWED_ORIGINS
        value: https://app.bookplus.example
