apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookplus
resources:
- admin-bff.yaml
- api-gateway.yaml
- auth-service.yaml
- cart-service.yaml
- catalog-service.yaml
- inventory-service.yaml
- notification-service.yaml
- order-service.yaml
- payment-service.yaml
- report-service.yaml
