version: "3.9"

services:

  payment-postgres:
    image: postgres:16-alpine
    container_name: payment-postgres
    environment:
      POSTGRES_DB:       payment_db
      POSTGRES_USER:     payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5437:5432"
    volumes:
      - payment-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.8.0
    container_name: payment-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    ports:
      - "9092:9092"
    volumes:
      - payment-kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 15s
      timeout: 10s
      retries: 10

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    environment:
      SERVER_PORT:                    8086
      PAYMENT_DB_URL:                 jdbc:postgresql://payment-postgres:5432/payment_db
      PAYMENT_DB_USER:                payment_user
      PAYMENT_DB_PASS:                payment_pass
      KAFKA_BOOTSTRAP_SERVERS:        kafka:9092
      PAYMENT_JWT_PUBLIC_KEY_BASE64:  ${PAYMENT_JWT_PUBLIC_KEY_BASE64}
    ports:
      - "8086:8086"
    depends_on:
      payment-postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8086/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 5

volumes:
  payment-postgres-data:
  payment-kafka-data:
