{{- $g := . }}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    {{- include "bookplus.labels" $g | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      name: http
---
{{- end }}
